### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by DarkSkull91** [SexyBeast233/SecBooks#2]
Hi, could you translate in english without a translator?

**Comment by SexyBeast233** [comment]
这个项目为2021年前后 ，用于个人收集使用，翻译成英文的工程量实在是太大 。这里建议以中间件或相关技术为关键词，使用evething进行搜索。

This project was for personal collection around 2211, and the amount of translation into English was too large. It is recommended to search with evethin using middleware or related technologies as keywords.
